### ISSUE TITLE
Toggle Filters

### ISSUE THREAD

**Issue by Dontorpedo** [optimistdigital/nova-detached-filters#1]
Wow, great package!

could you make the parent div open/closeable? that would be great!

sometimes one needs the filters not allways so they can stay closed and if needed open.

thx

**Comment by KasparRosin** [comment]
Hey!

Thank you for this suggestion. 
This functionality is now available in [[1.0.1]](https://github.com/optimistdigital/nova-detached-filters/releases/tag/1.0.1)
