### ISSUE TITLE
Boolean filters aligned horizontally

### ISSUE THREAD

**Issue by asivaneswaran** [optimistdigital/nova-detached-filters#12]
Hi,

I was wondering if it would be possible to align the different options of a BooleanFilter horizontally instead of vertically?

**Comment by KasparRosin** [comment]
There isn't one an implementing something that would force boolean filters to be in a row wouldn't fit the package in my view. 
I searched for other boolean filter packages that would enable this and couldn't find any so here are my recommendations. 

Moving over to a multiselect package to replace the boolean filter [nova-multiselect-filter](https://github.com/optimistdigital/nova-multiselect-filter), but if you only have 2-3 items in your boolean filter, this won't make much sense.

Alternatively you can look into `Nova::enableThemingClasses();` and changing the css of the boolean filter in detached-filters card yourself.
