### ISSUE TITLE
Filters disappearing on resources which aren't using detached filters

### ISSUE THREAD

**Issue by goldmerc** [optimistdigital/nova-detached-filters#17]
I just noticed that my resources which aren't using a NovaDetachedFilters card are losing their filters from the the standard Nova filter dropdown.

If I add the HasDetachedFilters trait to the resource class, the filter re-appears in the standard dropdown.

Is this the intended behaviour? 

Thanks

**Comment by LouisHrg** [comment]
I second this, the package is breaking every filters in my applications (I use it in 4 production applications). I'll try to do a PR if I manage to find the time

**Comment by KasparRosin** [comment]
https://github.com/optimistdigital/nova-detached-filters/blob/master/resources/js/components/FilterMenu.vue#L124

It appears this line might be causing the issue.

**Comment by KasparRosin** [comment]
@LouisHrg If you can create a pull request, i'll merge it.

If i have some time in the future, i'll try to find a solution that wont result in having to override filter-menu component.

**Comment by 00GeekInside00** [comment]
any updates on this issue?

**Comment by KasparRosin** [comment]
Released version 1.0.13 that should fix this issue.

Let me know if there are any more problems!
