### ISSUE TITLE
persitFilters() globally set for all users

### ISSUE THREAD

**Issue by stardothosting** [optimistdigital/nova-detached-filters#21]
When user "A" sets a persistent filter, user "B" logs in and sees that persistent filter setting applied.

I was expecting this functionality to be a per-user setting since my implementation has hundreds of users using these filters in many different ways. There would be many conflicts of persistent filter settings since this appears to be global. 

Is there any way to make this a per-user persistence?

Thanks!

**Comment by KasparRosin** [comment]
We are storing the persisted filters in localStorage, so unless the user A and B are using the same computer with the same login, the state should not be shared.
