### ISSUE TITLE
Select All/None feature for Boolean Filters?

### ISSUE THREAD

**Issue by vesper8** [optimistdigital/nova-detached-filters#22]
I have a Boolean filter with many values (over 15 checkboxes) and it would very useful to me if there was a "Select All" / "Select None" functionality.

Is there currently a way to implement this kind of functionality?

Thanks

**Comment by KasparRosin** [comment]
Hey, I don't think this feature is suitable for this package.
I think this feature would be more suited inside a custom boolean filter component.
