### ISSUE TITLE
Problem with toggle

### ISSUE THREAD

**Issue by goldmerc** [optimistdigital/nova-detached-filters#5]
When the card is toggled, the fields are invisible but still selectable. Please see attached screen shot. This also means that the search box can not be used.

<img width="984" alt="Screenshot 2020-10-28 at 16 25 29" src="https://user-images.githubusercontent.com/1322182/97466204-c0e59100-193a-11eb-9585-e79c3975f460.png">

(ps. sorry to be bombarding you with issues!)

**Comment by KasparRosin** [comment]
Fixed in [1.0.6](https://github.com/optimistdigital/nova-detached-filters/releases/tag/1.0.6), Thank you!
