### ISSUE TITLE
Styles messed up with Nova Multiselect Filter

### ISSUE THREAD

**Issue by andrius-urb** [optimistdigital/nova-detached-filters#6]
When using optimistdigital/nova-multiselect-filter, styles messed up when dropdown is opened for filter.
If below multiselect-filter is other filters - dropdown is not on top of them, but behind them.
Picture attached.

![problem](https://user-images.githubusercontent.com/71184703/97698457-36736d80-1ab1-11eb-8b6b-444eb1311bb1.png)

**Comment by andrius-urb** [comment]
Update: If I remove `nova-detached-filters-card` css class, from `<div class="card flex flex-col">`, input positions is messed up, but now dropdowns goes on top of other bottom filters, as it should.

**Comment by KasparRosin** [comment]
Thank you for reporting! Fixed and released in version [1.0.8]
