### ISSUE TITLE
persistfilters() / withToggle() with multiple resources

### ISSUE THREAD

**Issue by goldmerc** [optimistdigital/nova-detached-filters#8]
Hi Kaspar. At the moment, when you click the lock, persist filters is turned on for all resources that use the detached filters. Likewise, when you unclick the lock, it's turned off for all resources.

Similarly, when you toggle the card open / closed, the change effects all resources.

Personally, I think it would make more sense for each resource to have it's own state not effected by the settings used on a different resource.

It's just my opinion. Perhaps you prefer the way it works currently. Just thought I'd flag it.

**Comment by KasparRosin** [comment]
You're right, this does make a lot of sense. I've implemented this and released [1.0.9]. Thank you

**Comment by maaak7** [comment]
@KasparRosin, sorry for bothering you, but I get this problem with 2.0.3 version. Did you fix it?
