### ISSUE TITLE
Style on per page option

### ISSUE THREAD

**Issue by andrius-urb** [optimistdigital/nova-detached-filters#9]
If per page records choosen 100+ (three digits), style needs to be fixed, because arrow goes on top of number 👍 

![page](https://user-images.githubusercontent.com/71184703/97776320-c0820b80-1b6f-11eb-82dd-88adaaba0997.png)

**Comment by KasparRosin** [comment]
I was unable to reproduce this. I tested with 100 & 1000, both worked as expected. 
Do you have any project css that could override the width of the select?

**Comment by andrius-urb** [comment]
Sorry, my bad. `padding-right` was assigned to `.form-select` class, so it messed up this dropdown :)
